# Generated by Django 2.1.7 on 2019-02-16 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tool',
            options={'permissions': (('authorize_tool', 'Can authorize this tool'),)},
        ),
    ]
