# Generated by Django 2.1.7 on 2019-02-16 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0002_auto_20190216_0335'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tool',
            options={},
        ),
    ]
