# Generated by Django 2.1.2 on 2018-10-20 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='current_member',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='member',
            name='rfid_tag_id',
            field=models.CharField(default=1234, max_length=128),
            preserve_default=False,
        ),
    ]
