# Generated by Django 2.1.2 on 2018-10-20 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_auto_20181020_0302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='current_member',
        ),
        migrations.AlterField(
            model_name='member',
            name='authorized_tools',
            field=models.ManyToManyField(blank=True, to='tools.Tool'),
        ),
    ]
