# Generated by Django 2.1.7 on 2019-02-13 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_auto_20181020_0408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='rfid_tag_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
